version: "3.8"

services:
  backend:
    container_name: backend
    build:
      context: ./server
    ports:
      - 8000:8000
    depends_on:
      - database

  frontend:
    container_name: frontend
    build:
      context: ./frontend

  database:
    container_name: database
    restart: always
    
volumes:
  database: