version: "3.8"

services:  
  mongodb:
    container_name: mongodb
    image: mongo
    ports:
      - "27017:27017"
    restart: always

  chat-client:
    container_name: chat-client
    build:
      context: ./client
    ports:
      - "4000:4000"
    restart: always

  chat-server:
    container_name: chat-server
    build:
      context: ./server
    ports:
      - 8000:8000
    restart: always
    depends_on:
      - mongodb

volumes:
  mongodb: