version: "3.8"

services:
  redis:
    container_name: test-redis
    image: redis
    ports:
      - "6379:6379"
    restart: always
  
  mongodb:
    container_name: test-mongodb
    image: mongo
    ports:
      - "27017:27017"
    restart: always

  frontend:
    container_name: frontend
    build:
      context: ./frontend
    ports:
      - "4000:4000"
    restart: always
    depends_on:
      - backend

  backend:
    container_name: backend
    build:
      context: ./backend
    ports:
      - 8000:8000
    restart: always
    depends_on:
      - mongodb
      - redis
    
volumes:
  mongodb: